### ISSUE TITLE
Angular 4 template (dev branch) : problem with version 2.x.x of ng-packagr

### ISSUE THREAD

**Issue by mvidailhet** [geeklearningio/gl-swagger-generator#67]
The package generated has a dev-dependency on ng-packagr 2.0.0. But it creates errors:
```
Error: Cannot find module 'tsickle/src/tsickle'
```

The ng-packagr changelog says the 2.x versions are for angular 5 : [https://github.com/dherges/ng-packagr/blob/master/CHANGELOG.md#200-2018-02-05](https://github.com/dherges/ng-packagr/blob/master/CHANGELOG.md#200-2018-02-05)

Solution : set ng-packagr version to 1.7.0 to fix this (tested)

**Comment by sandorfr** [comment]
yep we can safely revert to 1.7.0 consumers can override it to a newer version if they don't need angular 4.x support, as with other dependencies.
